apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-eitm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-eitm@sha256:c718e3c922fa6db1d782728a398e432fdfdc54b04aed7e4969c9dfb6fff77e4f
        name: my-nodejs
        resources: {}
status: {}
